// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: models/model_tournament.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Bb_Mobile_OddinTreeWs_Tournament {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var info: Bb_Mobile_OddinTreeWs_Tournament.TournamentInfo {
    get {return _info ?? Bb_Mobile_OddinTreeWs_Tournament.TournamentInfo()}
    set {_info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  var hasInfo: Bool {return self._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  mutating func clearInfo() {self._info = nil}

  var matches: [Bb_Mobile_OddinTreeWs_Match] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct TournamentInfo {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: String = String()

    var sportID: String = String()

    var name: String = String()

    var abbreviation: String = String()

    var order: Int32 = 0

    var iconPath: String = String()

    var matchesCount: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _info: Bb_Mobile_OddinTreeWs_Tournament.TournamentInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "bb.mobile.oddin_tree_ws"

extension Bb_Mobile_OddinTreeWs_Tournament: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Tournament"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "info"),
    2: .same(proto: "matches"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._info) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.matches) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._info {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.matches.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.matches, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bb_Mobile_OddinTreeWs_Tournament, rhs: Bb_Mobile_OddinTreeWs_Tournament) -> Bool {
    if lhs._info != rhs._info {return false}
    if lhs.matches != rhs.matches {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Bb_Mobile_OddinTreeWs_Tournament.TournamentInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Bb_Mobile_OddinTreeWs_Tournament.protoMessageName + ".TournamentInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "sport_id"),
    3: .same(proto: "name"),
    4: .same(proto: "abbreviation"),
    5: .same(proto: "order"),
    6: .standard(proto: "icon_path"),
    7: .standard(proto: "matches_count"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sportID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.abbreviation) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.order) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.iconPath) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.matchesCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.sportID.isEmpty {
      try visitor.visitSingularStringField(value: self.sportID, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    if !self.abbreviation.isEmpty {
      try visitor.visitSingularStringField(value: self.abbreviation, fieldNumber: 4)
    }
    if self.order != 0 {
      try visitor.visitSingularInt32Field(value: self.order, fieldNumber: 5)
    }
    if !self.iconPath.isEmpty {
      try visitor.visitSingularStringField(value: self.iconPath, fieldNumber: 6)
    }
    if self.matchesCount != 0 {
      try visitor.visitSingularInt32Field(value: self.matchesCount, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bb_Mobile_OddinTreeWs_Tournament.TournamentInfo, rhs: Bb_Mobile_OddinTreeWs_Tournament.TournamentInfo) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.sportID != rhs.sportID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.abbreviation != rhs.abbreviation {return false}
    if lhs.order != rhs.order {return false}
    if lhs.iconPath != rhs.iconPath {return false}
    if lhs.matchesCount != rhs.matchesCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
